# Generated by Django 2.2.6 on 2019-11-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='comp_addr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lunch_noti_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='schedule_noti_enable',
            field=models.BooleanField(default=True),
        ),
    ]
