# Generated by Django 2.2.6 on 2019-11-26 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191121_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
