# Generated by Django 2.2.6 on 2019-11-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20191119_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
