# Generated by Django 2.2.6 on 2019-11-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_comment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='people',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
